### ISSUE TITLE
nbprocess_quarto bug

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbprocess#37]
@jph00 @hamelsmu 

I am unable to generate docs as I walk through an end to end example.  I get different errors depending on what version of python I am using.  I am having a hard time laying this out clearly, but I've given it a shot and I am happy to hop on and troubleshoot live if helpful.

# Environment Repro

1. Create conda env
    + p38:  `conda create --name p38 python=3.8`
    + p39:  `conda create --name p39 python=3.9`
    + p310: `conda create --name p310 python=3.10`
2. Editable install of nbprocess via `pip install -e .`

# Error Repro

Stack traces are below.  These are generated by cloning [this repo](https://github.com/Isaac-Flath/deck_of_cards) and running `make docs`. 

>Note:  Between attempts I would reset to that repository as you get a different error message if no `README.md` exists, and `make docs` is currently removing the `README.md` file.  Since I think it's likely that this fix will also fix that - and it seems to be a different issue - I haven't included stack traces for that here to keep the issue somewhat follow-able and focused.

# 3.8 Stack Trace

I think this is a [python bug](https://bugs.python.org/issue32689) that is fixed in later versions of python

```bash
(p38) isaacflath@Isaacs-MacBook-Pro deck_of_cards % make docs
nbprocess_export
pip install -e .
Obtaining file:///Users/isaacflath/github/deck_of_cards
Installing collected packages: deck-of-cards
  Attempting uninstall: deck-of-cards
    Found existing installation: deck-of-cards 0.0.1
    Uninstalling deck-of-cards-0.0.1:
      Successfully uninstalled deck-of-cards-0.0.1
  Running setup.py develop for deck-of-cards
Successfully installed deck-of-cards-0.0.1
nbprocess_quarto
ERROR: SyntaxError: Unexpected token N in JSON at position 0
ERROR: SyntaxError: Unexpected token N in JSON at position 0
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/p38/bin/nbprocess_quarto", line 33, in <module>
    sys.exit(load_entry_point('nbprocess', 'console_scripts', 'nbprocess_quarto')())
  File "/Users/isaacflath/opt/miniconda3/envs/p38/lib/python3.8/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/isaacflath/github/nbprocess/nbprocess/cli.py", line 286, in nbprocess_quarto
    shutil.move(tmp_doc_path/'README.md', cfg_path) # README.md is temporarily in the nbs/docs folder
  File "/Users/isaacflath/opt/miniconda3/envs/p38/lib/python3.8/shutil.py", line 787, in move
    real_dst = os.path.join(dst, _basename(src))
  File "/Users/isaacflath/opt/miniconda3/envs/p38/lib/python3.8/shutil.py", line 750, in _basename
    return os.path.basename(path.rstrip(sep))
AttributeError: 'PosixPath' object has no attribute 'rstrip'
make: *** [docs] Error 1
```

# 3.9/3.10 stack trace

I tested newer versions of python to see if the error goes away, since my hypothesis was that there was a python 3.8 bug causing the issue.  In 3.9/3.10 I seem to get a different error.  Here is the stack trace for 3.9/3.10 versions.

```bash
(p39) isaacflath@Isaacs-MacBook-Pro deck_of_cards % make docs 
nbprocess_export
pip install -e .
Obtaining file:///Users/isaacflath/github/deck_of_cards
Installing collected packages: deck-of-cards
  Running setup.py develop for deck-of-cards
Successfully installed deck-of-cards-0.0.1
nbprocess_quarto
ERROR: SyntaxError: Unexpected token N in JSON at position 0
ERROR: SyntaxError: Unexpected token N in JSON at position 0
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/shutil.py", line 823, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/isaacflath/github/deck_of_cards/docs/README.md' -> '/Users/isaacflath/github/deck_of_cards/README.md'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/p39/bin/nbprocess_quarto", line 33, in <module>
    sys.exit(load_entry_point('nbprocess', 'console_scripts', 'nbprocess_quarto')())
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/isaacflath/github/nbprocess/nbprocess/cli.py", line 286, in nbprocess_quarto
    shutil.move(tmp_doc_path/'README.md', cfg_path) # README.md is temporarily in the nbs/docs folder
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/shutil.py", line 843, in move
    copy_function(src, real_dst)
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/isaacflath/github/deck_of_cards/docs/README.md'
make: *** [docs] Error 1
```

**Comment by hamelsmu** [comment]
@jph00 I took a look at this and it looks like quarto is complaining there is invalid JSON.  For good measure, I added a debug flag to intercept the JSON going in/out of the filter in #39 The json seems valid to me.  The only thing I can think of now is to contact JJ to see if he has any ideas.
