### ISSUE TITLE
export bug with patch decorator

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbprocess#45]
@hamelsmu @jph00 

`nbprocess_export` fails when you use [fastcore monkey patching](https://fastcore.fast.ai/basics.html#patch_to).  I used `patch_to`, but this same error applies with the alternate `patch` decorator.

To recreated error:
- Clone [deck of cards repo](https://github.com/isaac-Flath/deck_of_cards)
- Run `nbprocess_export` to verify it runs
- Add a new cells with the following code to `00_card.ipynb` (after `Card` class is defined)

```python
#|export
from fastcore.all import *
```
```python
#|export
@patch_to(Card)
def bar(self): pass
```

- Run `nbprocess_export` and you will get the stack trace below

```bash
(untidyverse) iflath@pop-os:~/github/deck_of_cards$ nbprocess_export 
Traceback (most recent call last):
  File "/home/iflath/miniconda3/envs/untidyverse/bin/nbprocess_export", line 33, in <module>
    sys.exit(load_entry_point('nbprocess', 'console_scripts', 'nbprocess_export')())
  File "/home/iflath/miniconda3/envs/untidyverse/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 136, in nbprocess_export
    build_modidx()
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 107, in build_modidx
    if file.name[0]!='_': DocLinks(file, doc_func, _fn).build_index()
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 85, in build_index
    self.update_syms()
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 78, in update_syms
    exp += L(get_patch_name(o) for o in trees).filter()
  File "/home/iflath/miniconda3/envs/untidyverse/lib/python3.9/site-packages/fastcore/foundation.py", line 97, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/home/iflath/miniconda3/envs/untidyverse/lib/python3.9/site-packages/fastcore/foundation.py", line 105, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/home/iflath/miniconda3/envs/untidyverse/lib/python3.9/site-packages/fastcore/basics.py", line 59, in listify
    elif is_iter(o): res = list(o)
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 78, in <genexpr>
    exp += L(get_patch_name(o) for o in trees).filter()
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 68, in get_patch_name
    if  isinstance(tree, (ast.FunctionDef,ast.AsyncFunctionDef)) and _is_patch(tree):
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 53, in _is_patch
    def _is_patch(o): return any([1 for d in o.decorator_list if _decor_id(d).startswith('patch')])
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 53, in <listcomp>
    def _is_patch(o): return any([1 for d in o.decorator_list if _decor_id(d).startswith('patch')])
  File "/home/iflath/github/nbprocess/nbprocess/doclinks.py", line 45, in _decor_id
    return d.func.value.id
AttributeError: 'Name' object has no attribute 'value'
```

**Comment by Isaac-Flath** [comment]
@jph00 

It's functional and gets me what I need, but there's two oddities I thought I'd mention so you are aware/can decide whether you want to do anything about them or not.  The repo is updat

1. The `__all__` gets put in the middle of the py module.  The `Card` class is at the top, then the `__all__`, and then the patched function is at the end.  I would prefer the `__all__` be at either the top or bottom of the file rather than in the middle.  [Link to py module file](https://github.com/Isaac-Flath/deck_of_cards/blob/main/deck_of_cards/card.py)
2. `show_doc` displays the patched method slightly differently than a normally defined method.  The patched method shows `self` as an argument, where the normal defined methods do not.

<img width="374" alt="Screen Shot 2022-06-03 at 6 38 32 PM" src="https://user-images.githubusercontent.com/6256508/171963260-3ee83fbc-3874-4d74-a322-9733e11960d4.png">

**Comment by Isaac-Flath** [comment]
Also, I think `get_patch_name` is defined twice in `04b_doclinks` now and the first one should be removed.

**Comment by jph00** [comment]
> 1. The `__all__` gets put in the middle of the py module.  The `Card` class is at the top, then the `__all__`, and then the patched function is at the end.  I would prefer the `__all__` be at either the top or bottom of the file rather than in the middle.  [Link to py module file](https://github.com/Isaac-Flath/deck_of_cards/blob/main/deck_of_cards/card.py)

The reason for that is that you've got all the imports and class definition in a single cell. In nbdev imports need to be in a separate cell to other code. (It's a good idea to have each cell just do one thing anyway, as a matter of writing style -- but for imports it's actually required, not just recommended!)

**Comment by Isaac-Flath** [comment]
nbdev1 does handle this scenario in the example repo I believe in [this notebook](https://github.com/fastai/deck_of_cards/blob/master/00_card.ipynb).  that created this [py module](https://github.com/fastai/deck_of_cards/blob/master/deck_of_cards/card.py)

But I agree that it'd be better style to break out the cell and that it's not a huge deal if nbdev2 doesn't handle this.
