### ISSUE TITLE
Python 3.9: Linkify causes issues with built libraries, creating new ones, and deploying the docs

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbprocess#80]
Caused by https://github.com/fastai/nbprocess/pull/75

When I try to import `nbprocess.processors` I get:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <module>
      4 from nbprocess.imports import *
      5 from nbprocess.maker import *
----> 7 from nbprocess.processors import _default_exp

File /opt/conda/lib/python3.9/site-packages/nbprocess/processors.py:14, in <module>
     12 from .imports import *
     13 from .process import *
---> 14 from .lookup import *
     15 from .showdoc import *
     17 from execnb.nbio import *

File /opt/conda/lib/python3.9/site-packages/nbprocess/lookup.py:53, in <module>
     50         return  _settings.get('strip_libs',_settings.get('lib_name')).split()
     51     except FileNotFoundError: return 'nbprocess'
---> 53 nbprocess_lookup = NbdevLookup(_libs())
     55 # %% ../nbs/13_lookup.ipynb 14
     56 @patch
     57 def _link_sym(self:NbdevLookup, m):

File /opt/conda/lib/python3.9/site-packages/nbprocess/lookup.py:34, in NbdevLookup.__init__(self, strip_libs, incl_libs, skip_mods)
     32 py_syms = merge(*L(o['syms'].values() for o in self.entries.values()).concat())
     33 for m in strip_libs:
---> 34     _d = self.entries[m]
     35     stripped = {remove_prefix(k,f"{mod}."):v
     36                 for mod,dets in _d['syms'].items() if mod not in skip_mods
     37                 for k,v in dets.items()}
     37                 for k,v in dets.items()}
     38     py_syms = merge(stripped, py_syms)

KeyError: 'testing_grounds'
```

This also happens if I try `nbprocess_new`:
```bash
(base) jovyan@43794e78e253:~/local/zach$ nbprocess_new 
Traceback (most recent call last):
  File "/opt/conda/bin/nbprocess_new", line 5, in <module>
    from nbprocess.cli import nbprocess_new
  File "/opt/conda/lib/python3.9/site-packages/nbprocess/cli.py", line 10, in <module>
    from .processors import *
  File "/opt/conda/lib/python3.9/site-packages/nbprocess/processors.py", line 14, in <module>
    from .lookup import *
  File "/opt/conda/lib/python3.9/site-packages/nbprocess/lookup.py", line 53, in <module>
    nbprocess_lookup = NbdevLookup(_libs())
  File "/opt/conda/lib/python3.9/site-packages/nbprocess/lookup.py", line 48, in _libs
    modidx = import_module(f"{get_config()['lib_name']}._modidx")
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '{lib_name}'
```

Here's also a log of the docs failing to deploy with a similar error: https://github.com/muellerzr/nbprocess-sandbox/runs/6976643483?check_suite_focus=true

cc @hamelsmu

**Comment by hamelsmu** [comment]
re the error you are getting when running `nbprocess_new`: 

```
No module named '{lib_name}' 
```

This makes me think something is wrong with your `settings.ini` maybe?  Can you check that?

**Comment by muellerzr** [comment]
@hamelsmu this is at the start of running the `nbdev_new` command, I haven't even entered any params in 🤷
