### ISSUE TITLE
make docs needs pip install of lib being developed

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbprocess#84]
@hamelsmu 

I cannot use `make docs` unless I pip install the library I am developing first.   

This was done using this code base https://github.com/Isaac-Flath/trading-testing

See below for example where I:
1. Run `make docs` and get error & stack trace
1. Run `pip install -e .` to install my library
1. Rerun `make docs` and get success

```bash
(fresh-nbprocess) isaacflath@Isaacs-MacBook-Pro trading-testing % make docs
nbprocess_export
nbprocess_quarto
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/bin/nbprocess_filter", line 8, in <module>
    sys.exit(nbprocess_filter())
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/cli.py", line 107, in nbprocess_filter
    NBProcessor(nb=nb, procs=filt.procs(), preprocs=filt.preprocs(), postprocs=filt.postprocs()).process()
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/process.py", line 104, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/process.py", line 88, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/processors.py", line 25, in add_links
    nl = NbdevLookup(libs())
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/lookup.py", line 48, in libs
    modidx = import_module(f"{get_config()['lib_name']}._modidx")
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tradingtesting'
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/bin/nbprocess_filter", line 8, in <module>
    sys.exit(nbprocess_filter())
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/cli.py", line 107, in nbprocess_filter
    NBProcessor(nb=nb, procs=filt.procs(), preprocs=filt.preprocs(), postprocs=filt.postprocs()).process()
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/process.py", line 104, in process
    for cell in self.nb.cells: self._process_cell(cell)
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/process.py", line 88, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/processors.py", line 25, in add_links
    nl = NbdevLookup(libs())
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages/nbprocess/lookup.py", line 48, in libs
    modidx = import_module(f"{get_config()['lib_name']}._modidx")
  File "/Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tradingtesting'
```

```bash
(fresh-nbprocess) isaacflath@Isaacs-MacBook-Pro trading-testing % pip install -e .
Obtaining file:///Users/isaacflath/github/trading-testing
Requirement already satisfied: fastcore in /Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages (from tradingtesting==0.0.1) (1.4.5)
Collecting pandas
  Using cached pandas-1.4.2-cp310-cp310-macosx_10_9_x86_64.whl (11.1 MB)
Requirement already satisfied: pip in /Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages (from fastcore->tradingtesting==0.0.1) (21.2.4)
Requirement already satisfied: packaging in /Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages (from fastcore->tradingtesting==0.0.1) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages (from packaging->fastcore->tradingtesting==0.0.1) (3.0.9)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting numpy>=1.21.0
  Using cached numpy-1.22.4-cp310-cp310-macosx_10_15_x86_64.whl (17.7 MB)
Requirement already satisfied: six>=1.5 in /Users/isaacflath/opt/miniconda3/envs/fresh-nbprocess/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->tradingtesting==0.0.1) (1.16.0)
Installing collected packages: pytz, python-dateutil, numpy, pandas, tradingtesting
  Running setup.py develop for tradingtesting
Successfully installed numpy-1.22.4 pandas-1.4.2 python-dateutil-2.8.2 pytz-2022.1 tradingtesting-0.0.1
```

```bash
(fresh-nbprocess) isaacflath@Isaacs-MacBook-Pro trading-testing % make docs
nbprocess_export
nbprocess_quarto
[1/4] 10_datamodule.ipynb
[2/4] 30_models.ipynb
[3/4] 00_utils.ipynb
[4/4] index.ipynb

Output created: docs/index.html

pandoc -o README.md
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  standalone: true
  default-image-extension: png
  
metadata
  title: Project name here
  description: Summary description here.
  
Output created: docs/README.md
```

**Comment by hamelsmu** [comment]
This has been fixed by @jph00 just now, now `make docs` will install the dependencies.  Thank you @Isaac-Flath
