### ISSUE TITLE
nbprocess_new errors out at description

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/nbprocess#89]
After asking for author email, `nbprocess_new` seems to fail with the following error:
```
`settings.ini` updated with configuration values.
Traceback (most recent call last):
  File "/miniconda3/bin/nbprocess_new", line 8, in <module>
    sys.exit(nbprocess_new())
  File "/miniconda3/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/miniconda3/lib/python3.9/site-packages/nbprocess/cli.py", line 272, in nbprocess_new
    settings = settings.format(**config)
KeyError: 'description'
```
This fails on the pypi version 0.0.3 and installing from git.

This is in an empty folder/directory. If there is a requirement `nbprocess_new` to be in a new cloned git repo, then it should probably gracefully error out at the beginning with a warning message.

Also, some of the questions are a bit vague. I assume this is asking for my GitHub username and default branch, but it could be more specific.
```
user:
Please enter the following information:

branch:
Please enter the following information:
```

**Comment by warner-benjamin** [comment]
I notice that [the tutorial](https://nbprocess.fast.ai/tutorial.html) does mention a git repo requirement, but I didn't notice the tutorial while skimming through the docs as it's all the way at the bottom of the nav list
